### ISSUE TITLE
Bid notification for league members

### ISSUE THREAD

**Issue by AndyGOBrien** [SteveF92/FantasyCritic#18]
Can there be some kind of hook when a bid is made? It would be awesome to create a discord bot or something that notifies when bids are made, how much the bid was for, a link to open critic for game information, etc...

Thoughts?

**Comment by SteveF92** [comment]
Bids are designed to be secret. Honestly that's something I'm really hesitant to change because it would really change the nature of the game. The system is based off of FAAB in fantasy football. If you want a good explanation of that, you can read this article:

https://www.thefantasyfootballers.com/articles/league-needs-change-waiver-system-asap/

**Comment by AndyGOBrien** [comment]
Ah okay. Seems cool. It also seems like it could be a configurable option? 

For example, one of the main draws for me and the players in my league is the discussion that happens surrounding the games. Also, unlike football, there are massive amounts of games that are announced for release within the year, which makes it very easy for those of us who pay very close attention to grab up a game for $0.00 - $1.00 unnoticed, giving a pretty massive disadvantage to the more casual gamers in the league.

Having it notify the members of the league that a game is being bid on with a link to the game info, with or without the bid amount, could create some very fun competition through bidding wars as well as generating discussion surrounding the game.

I see your point though and understand the secrecy aspect of it as well.

**Comment by AndyGOBrien** [comment]
Really like the site btw!
