### ISSUE TITLE
Projected points mismatch

### ISSUE THREAD

**Issue by AndrewKralovec** [SteveF92/FantasyCritic#4]
So, im not 100% this is a bug. However, when looking at the standing on the league page. I noticed that the projected points from the `/api/League/GetLeagueYear` request, was not matching the values on screen. Is this a bug, or is there an additional calculation to get the points that are rendered to you in the view? If, so, i did not see it in the [vue component](https://github.com/SteveF92/FantasyCritic/search?q=totalProjectedPoints&unscoped_q=totalProjectedPoints)
 (screen shot attached)

Steps to reproduce:

- Login in as user. 
- Navigate to your league page. 
- Look at the league standings on page and compare them with the values from the `/api/League/GetLeagueYear` request json result. 
- You should see that totalProjectedPoints does not match the values on the screen. 

![unknown](https://user-images.githubusercontent.com/6210337/62504938-402ff780-b7c0-11e9-80d2-c719ee7a7956.png)

**Comment by SteveF92** [comment]
You've uncovered a currently hidden, soon-to-be feature. If you look inside the "players" portion of the response, you'll see that each player has two different projected points right now. The "simple" ones are the ones I'm showing in the site. The "advanced" ones are currently hidden but hopefully will be ready to be shown soon. 

The ones in the publishers section are just the advanced ones because that's all I needed for the views, and I wasn't thinking about API users at the time.

**Comment by AndrewKralovec** [comment]
@SteveF92 , thanks for the clarification, i should have been looking at this [component](https://github.com/SteveF92/FantasyCritic/blob/c2f926bfb3c697d0d0279bc6606bb09ae73ee573/FantasyCritic.Web/ClientApp/components/pages/league.vue).

**Comment by AndrewKralovec** [comment]
@SteveF92 , thanks for the clarification, i should have been looking at this [component](https://github.com/SteveF92/FantasyCritic/blob/c2f926bfb3c697d0d0279bc6606bb09ae73ee573/FantasyCritic.Web/ClientApp/components/pages/league.vue).
